name: Trigger auto deployment for lab01-container-app-test02

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ BackEnd ]
    paths:
    - '**'
    - '.github/workflows/lab01-container-app-test02-AutoDeployTrigger-7291660c-a9ff-4ab8-b444-0b9790b88530.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LAB01CONTAINERAPPTEST02_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.DOCKER_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_PASSWORD }}
          containerAppName: lab01-container-app-test02
          resourceGroup: NULP_resources_01
          targetPort: 1234
          imageToBuild: littlehydron/images_for_lab1:grainsense_image
